function spmx_updatejobs(jobs)

% no input given
if nargin < 1 || ...
   ~iscell(jobs) || ...
    isempty(jobs) || ...
   ~isstruct(jobs{1}) || ...
    numel(jobs{1}) ~= 1

    % request file
    [matfile, matpath] = uigetfile({'*.mat', 'SPM job(s) file (*.mat)'}, ...
        'Please select an SPM job file for updating...');
    if isequal(matfile, 0) || ...
        isequal(matpath, 0) || ...
        isempty(matfile)
        return;
    end
    if isempty(matpath)
        matpath = pwd;
    end
    fullmatfile = [matpath '/' matfile];
    try
        jobs = load(fullmatfile);
    catch ne_eo;
        rethrow(ne_eo);
    end
    if ~isfield(jobs, 'jobs') && ...
       ~isfield(jobs, 'matlabbatch') || ...
       ((isfield(jobs, 'jobs') && ...
         (~iscell(jobs.jobs) || ...
          isempty(jobs.jobs) || ...
          ~isstruct(jobs.jobs{1}))) || ...
        (isfield(jobs, 'matlabbatch') && ...
         (~iscell(jobs.matlabbatch) || ...
          isempty(jobs.matlabbatch) || ...
          ~isstruct(jobs.matlabbatch) || ...
          ~isfield(jobs.matlabbatch, 'spm'))))
        error( ...
            'neuroelf:BadFileContent', ...
            'Not an SPM job file: %s.', ...
            matfile ...
        );
    end

% otherwise
else

    % pack into structure
    if isfield(jobs, 'spm')
    end
end

% get list of jobs (names, info)
jobinfo = 1;
