function ti = setlayertrans(ti, l, tr)
% transimg::setlayertrans  - set trans parameter of a layer of an image

% Version:  v0.9c
% Build:    12012202
% Date:     Jan-22 2012, 1:55 AM EST
% Author:   Jochen Weber, SCAN Unit, Columbia University, NYC, NY, USA
% URL/Info: http://neuroelf.net/

% Copyright (c) 2012, Jochen Weber
% All rights reserved.
%
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
%     * Redistributions of source code must retain the above copyright
%       notice, this list of conditions and the following disclaimer.
%     * Redistributions in binary form must reproduce the above copyright
%       notice, this list of conditions and the following disclaimer in the
%       documentation and/or other materials provided with the distribution.
%     * Neither the name of Columbia University nor the
%       names of its contributors may be used to endorse or promote products
%       derived from this software without specific prior written permission.
%
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
% ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
% WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
% DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
% DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
% (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
% LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
% ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
% (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
% SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

% global variables for storage
global tiobj ...
       tiobjlup;

% check arguments
lup = find(tiobjlup == ti.L);
if numel(lup) ~= 1
    error( ...
        'transimg:ObjectRemoved', ...
        'Object removed from global storage.' ...
    );
end
if nargin < 3 || ...
   ~isa(l, 'double') || ...
    numel(l) ~= 1 || ...
    isinf(l) || ...
    isnan(l) || ...
    l < 1 || ...
    l > numel(tiobj(lup).Layer) || ...
    l ~= fix(l) || ...
    tiobj(lup).Layer(l).Type == 'f' || ...
   ~isa(tr, 'double') || ...
   (numel(tr) ~= 2 && ...
    numel(tr) ~= 3 && ...
    ~isequal(size(tr), [3, 3]) && ...
    ~isequal(size(tr), [4, 4])) || ...
    any(isinf(tr(:)) | isnan(tr(:))) || ...
   (tiobj(lup).Layer(l).Type == 'p' && ...
    (numel(tr) ~= 2 || ...
     any(tr < 0) || ...
     any((tr + [size(tiobj(lup).Layer(l).Pixel, 1), size(tiobj(lup).Layer(l).Pixel, 2)]) > ...
        [tiobj(lup).Height, tiobj(lup).Width]))) || ...
   (tiobj(lup).Layer(l).Type ~= 'p' && ...
    numel(tr) == 2)
    error( ...
        'transimg:BadArgument', ...
        'Invalid layer or transformation for partial/transformed content.' ...
    );
end

% reset IsRendered flag
tiobj(lup).IsRendered = false;
tiobj(lup).Layer(l).IsRendered = false;

% set layer trans value
tiobj(lup).Layer(l).Trans = tr;
