function M = methods(S)
% xini::methods  - get methods of class

% Version:  v1.0
% Build:    16011315
% Date:     Jan-13 2016, 3:44 PM EST
% Author:   Jochen Weber, SCAN Unit, Columbia University, NYC, NY, USA
% URL/Info: http://neuroelf.net/

% Copyright (c) 2010, 2016, Jochen Weber
% All rights reserved.
%
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
%     * Redistributions of source code must retain the above copyright
%       notice, this list of conditions and the following disclaimer.
%     * Redistributions in binary form must reproduce the above copyright
%       notice, this list of conditions and the following disclaimer in the
%       documentation and/or other materials provided with the distribution.
%     * Neither the name of Columbia University nor the
%       names of its contributors may be used to endorse or promote products
%       derived from this software without specific prior written permission.
%
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
% ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
% WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
% DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
% DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
% (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
% LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
% ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
% (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
% SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

% stored in global storage
global xinimeth;
if isempty(xinimeth)
    xinimeth = struct( ...
        'display',      {{}}, ...
        'GetCaller',    {{}}, ...
        'GetChildren',  {{}}, ...
        'GetComplete',  {{}}, ...
        'GetFilename',  {{}}, ...
        'GetFoot',      {{}}, ...
        'GetHead',      {{}}, ...
        'GetID',        {{}}, ...
        'GetIniString', {{}}, ...
        'GetParents',   {{}}, ...
        'GetProtection',{{}}, ...
        'GetSection',   {{'^char$'}}, ...
        'GetSections',  {{}}, ...
        'GetSectionSettings', {{'^char$'}}, ...
        'GetSetting',   {{'^char$', '^char$'}}, ...
        'GetSectVals',  {{}}, ...
        'IsSection',    {{'^char$'}}, ...
        'IsSetting',    {{'^char$', '^char$'}}, ...
        'IsValid',      {{}}, ...
        'NewIniFile',   {{'[^char$'}}, ...
        'Release',      {{'[^char$'}}, ...
        'ReleaseAllFiles', {{}}, ...
        'Reload',       {{}}, ...
        'ReloadAllFiles', {{}}, ...
        'Remove',       {{'^char$', '[^char$'}}, ...
        'ResetClass',   {{}}, ...
        'Save',         {{}}, ...
        'SaveAs',       {{'^char$'}}, ...
        'SetComplete',  {{'^struct$'}}, ...
        'SetFoot',      {{'^char$'}}, ...
        'SetHead',      {{'^char$'}}, ...
        'SetIniString', {{'^char$'}}, ...
        'SetParent',    {{'^(double|xini)$'}}, ...
        'SetProtection',{{'^char$'}}, ...
        'SetSectVals',  {{'^logical$'}} ...
    );
end

% bogus check
if ~isxini(S)
    error( ...
        'xini:BadArgument', ...
        'Bad argument supplied to class method.' ...
    );
end

% return fieldnames
M = fieldnames(xinimeth);
