function create_age_h_figure
%CREATE_AGE_H_M_FIGURE
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c
%  XDATA1:  line xdata
%  YDATA1:  line ydata

%  Auto-generated by MATLAB on 02-Apr-2015 11:48:43
%  updated (JW) 28-Jul-2017 12:07:17

% use neuroelf
n = neuroelf;

% data (age:2017)
agerange = [28, 82];
agedata = { ...
    'LH',  30.11,   8,  1.00; ...
    'MA',  31.49,  10,  1.43; ...
    'NT',  43.09,  36,  2.40; ...
   'VPV',  45.79,  19,  1.73; ...
    'DS',  45.80,  31,  2.07; ...
    'NK',  46.08,  37,  2.31; ...
    'LD',  46.87,  40,  2.35; ...
    'SW',  47.88,  23,  1.28; ...
    'KO',  47.91,  70,  2.92; ...
    'CH',  50.74,  43,  2.87; ...
    'NB',  59.08,  46,  1.53; ...
    'GD',  60.23,  47,  1.62; ...
    'JM',  67.13,  53,  1.20; ...
    'RS',  69.48,  62,  1.41; ...
    'TH',  71.38, 112,  2.38; ...
    'NG',  72.97,  32,  0.70; ...
    'DH',  75.15,  70,  1.43; ...
    'HT',  80.43,  28,  0.74};

% store in individual variables
N1 = agedata(:, 1);
X1 = cat(1, agedata{:, 2});
Y1 = cat(1, agedata{:, 3}); YN = 'h'; YR = [0, 120];
Y2 = cat(1, agedata{:, 4}); YN2 = 'm'; YR2 = [0.5, 3.5];
nx = numel(N1);
  
% create figure, and add up to 2000 low-visible lines
figure1 = figure;
axes1 = axes;
l = zeros(2000, 1);
for lc = 2000:-1:1
    r1 = ceil(nx * rand(nx, 1));
    X1r = X1(r1, :);
    Y1r = Y1(r1, :);
    xx = [ones(nx, 1), X1r];
    b = n.fitrobustbisquare(xx, Y1r);
    if b(2) > 0
        l(lc) = line(agerange', b(1) + agerange' .* b(2), 'Parent', axes1);
    else
        l(lc) = [];
    end
end
set(l, 'LineWidth', 0.25, 'Color', [0.9, 0.9, 0.9]);

% create scatter
[axes1, rs] = n.robscatter(X1, Y1, struct('ax', axes1, 'hold', true, ...
    'cbands', true, 'cbandz', 3, ...
    'cweight', 0.5, 'dcolor', zeros(nx, 3), 'ocolor', [1, 1, 1]));
set(figure1, 'Position', [300, 300, 1152, 864]);
axch = get(axes1, 'Children');
set(axch(1:3), 'Color', [0, 0, 0], 'LineWidth', 1.5);
set(axch(4), 'MarkerEdgeColor', [0.5, 0.5, 0.5], 'MarkerFaceColor', 'flat', ...
    'SizeData', 72, 'CData', ...
    rs{1}.w(:, [1,1,1]) .* zeros(nx, 3) + (1 - rs{1}.w(:, [1,1,1])) .* ones(nx, 3));
set(figure1, 'Color', [1, 1, 1]);
set(axes1, 'FontSize', 14);
xlim(axes1, agerange);
ylim(axes1, YR);

% Create text
text('Parent', axes1, 'FontSize', 16, 'String', ...
    sprintf('r=%6.4f, p<%4.2f', n.robcorrcoef(X1,Y1), rs{1}.p(1) / 2), 'Position',[84, 48, 0]);

% label dots
XD = X1 - mean(X1);
XD = log(3 + log(1 + abs(XD))) .* sign(XD) - 0.5;
YD = Y1 - mean(Y1);
YD = log(3 + log(1 + abs(YD))) .* sign(YD);
for dc = 1:nx
    text('Parent', axes1, 'FontSize', 12, 'String', N1{dc}, ...
        'Position', [X1(dc) + XD(dc), Y1(dc) + YD(dc), 0]);
end

% Create xlabel
xlabel('age (y)');

% Create ylabel
ylabel([YN ' index']);

% Create title
title([YN ' index as a function of age'], 'FontSize', 16);

% save figure
print(figure1, '-r600', '-dpng', ['age-' YN '-corr2.png']);
im = imread(['age-' YN '-corr2.png']);
imr = n.image_resize(im, 0.5);
imwrite(imr, ['age-' YN '-corr2r.png']);

% close figure
delete(figure1);

% create second figure, and add up to 2000 low-visible lines
figure2 = figure;
axes2 = axes;
l = zeros(2000, 1);
for lc = 2000:-1:1
    r1 = ceil(nx * rand(nx, 1));
    X1r = X1(r1, :);
    Y2r = Y2(r1, :);
    xx = [ones(nx, 1), X1r];
    b = n.fitrobustbisquare(xx, Y2r);
    if b(2) < 0
        l(lc) = line(agerange', b(1) + agerange' .* b(2), 'Parent', axes2);
    else
        l(lc) = [];
    end
end
set(l, 'LineWidth', 0.25, 'Color', [0.9, 0.9, 0.9]);

% create scatter
[axes2, rs] = n.robscatter(X1, Y2, struct('ax', axes2, 'hold', true, ...
    'cbands', true, 'cbandz', 3, ...
    'cweight', 0.5, 'dcolor', zeros(nx, 3), 'ocolor', [1, 1, 1]));
set(figure2, 'Position', [300, 300, 1152, 864]);
axch = get(axes2, 'Children');
set(axch(1:3), 'Color', [0, 0, 0], 'LineWidth', 1.5);
set(axch(4), 'MarkerEdgeColor', [0.5, 0.5, 0.5], 'MarkerFaceColor', 'flat', ...
    'SizeData', 72, 'CData', ...
    rs{1}.w(:, [1,1,1]) .* zeros(nx, 3) + (1 - rs{1}.w(:, [1,1,1])) .* ones(nx, 3));
set(figure2, 'Color', [1, 1, 1]);
set(axes2, 'FontSize', 14);
xlim(axes2, agerange);
ylim(axes2, YR2);

% Create text
text('Parent', axes2, 'FontSize', 16, 'String', ...
    sprintf('r=%6.4f, p<%4.2f', n.robcorrcoef(X1,Y2), rs{1}.p(1) / 2), 'Position',[84, 48, 0]);

% label dots
XD = X1 - mean(X1);
XD = log(3 + log(1 + abs(XD))) .* sign(XD) - 0.5;
YD = 5 .* (Y2 - mean(Y2));
YD = 0.1 .* log(2 + log(1 + abs(YD))) .* sign(YD);
for dc = 1:nx
    text('Parent', axes2, 'FontSize', 12, 'String', N1{dc}, ...
        'Position', [X1(dc) + XD(dc), Y2(dc) + YD(dc), 0]);
end

% Create xlabel
xlabel('age (y)');

% Create ylabel
ylabel([YN2 ' index']);

% Create title
title([YN2 ' index as a function of age'], 'FontSize', 16);

% save figure
print(figure2, '-r600', '-dpng', ['age-' YN2 '-corr2.png']);
im = imread(['age-' YN2 '-corr2.png']);
imr = n.image_resize(im, 0.5);
imwrite(imr, ['age-' YN2 '-corr2r.png']);

% close figure
delete(figure2);
